---
printWidth: 80
trailingComma: es5
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
bracketSpacing: true
proseWrap: always # Tell Prettier to wrap Markdown files at the printWidth.

# Handle HTML files with Go templating code.
overrides:
  - files:
      - '*.html'
    options:
      parser: go-template
